### ISSUE TITLE
Code should be more pythonic

### ISSUE THREAD

**Issue by mikelane** [NARCOTIC/PY-NOOB#1]
The code [here](https://github.com/NARCOTIC/PY-NOOB/blob/4fa0434f4f857300186ab938f1a7139716b62a34/Lesson-002.py#L11-L15) could be simplified to just 

```python
print(string[:x])
```
If you're trying to introduce looping, this would be more pythonic:

```python
for c in string[:x]:
    print(c)
```

**Comment by NARCOTIC** [comment]
I [added](https://github.com/NARCOTIC/PY-NOOB/commit/920f0fb7fbf9b60061d71c60858127ed63a61894#diff-c9f283ea72a065eab08dfacd15cfd2c8) `print(string[:x])` to the code to get the idea _(but commented out)_. I did not change my code since that program shows how a **while loop** works. I've included **for loops** in [this program](https://github.com/NARCOTIC/PY-NOOB/blob/master/Lesson-003.py). Thanks for reporting the issue.
